"""
Callback data constants used throughout the Telegram bot.
"""

MENU_PREFIX = "menu_"
CALLBACK_NEW_TICKET = f"{MENU_PREFIX}new_ticket"
CALLBACK_MY_TICKETS = f"{MENU_PREFIX}my_tickets"
CALLBACK_TRACK_TICKET = f"{MENU_PREFIX}track_ticket"
CALLBACK_HELP = f"{MENU_PREFIX}help"
CALLBACK_LANGUAGE = f"{MENU_PREFIX}language"
CALLBACK_LOGIN = f"{MENU_PREFIX}login"
CALLBACK_INFRASTRUCTURE = f"{MENU_PREFIX}infrastructure"
CALLBACK_LOGOUT = f"{MENU_PREFIX}logout"

CALLBACK_CATEGORY_PREFIX = "category_"
CALLBACK_BRANCH_PREFIX = "branch_"
CALLBACK_LANGUAGE_PREFIX = "set_lang_"
CALLBACK_SKIP_ATTACHMENTS = "skip_attachments"
CALLBACK_FINISH_ATTACHMENTS = "finish_attachments"
CALLBACK_CHANGE_STATUS = f"{MENU_PREFIX}change_status"
CALLBACK_STATUS_PREFIX = "status_"
CALLBACK_INFRA_ACTION_PREFIX = "infra_action_"
CALLBACK_INFRA_TYPE_PREFIX = "infra_type_"
CALLBACK_INFRA_CONFIRM = f"{MENU_PREFIX}infra_confirm"
CALLBACK_INFRA_CANCEL = f"{MENU_PREFIX}infra_cancel"

__all__ = [
    "CALLBACK_NEW_TICKET",
    "CALLBACK_MY_TICKETS",
    "CALLBACK_TRACK_TICKET",
    "CALLBACK_HELP",
    "CALLBACK_LANGUAGE",
    "CALLBACK_LOGIN",
    "CALLBACK_LOGOUT",
    "CALLBACK_CATEGORY_PREFIX",
    "CALLBACK_BRANCH_PREFIX",
    "CALLBACK_LANGUAGE_PREFIX",
    "CALLBACK_SKIP_ATTACHMENTS",
    "CALLBACK_FINISH_ATTACHMENTS",
    "CALLBACK_CHANGE_STATUS",
    "CALLBACK_STATUS_PREFIX",
    "CALLBACK_INFRASTRUCTURE",
    "CALLBACK_INFRA_ACTION_PREFIX",
    "CALLBACK_INFRA_TYPE_PREFIX",
    "CALLBACK_INFRA_CONFIRM",
    "CALLBACK_INFRA_CANCEL",
]

