"""
Callback data constants used throughout the Telegram bot.
"""

MENU_PREFIX = "menu_"
CALLBACK_NEW_TICKET = f"{MENU_PREFIX}new_ticket"
CALLBACK_MY_TICKETS = f"{MENU_PREFIX}my_tickets"
CALLBACK_TRACK_TICKET = f"{MENU_PREFIX}track_ticket"
CALLBACK_HELP = f"{MENU_PREFIX}help"
CALLBACK_LANGUAGE = f"{MENU_PREFIX}language"
CALLBACK_LOGIN = f"{MENU_PREFIX}login"
CALLBACK_INFRASTRUCTURE = f"{MENU_PREFIX}infrastructure"
CALLBACK_LOGOUT = f"{MENU_PREFIX}logout"

CALLBACK_CATEGORY_PREFIX = "category_"
CALLBACK_BRANCH_PREFIX = "branch_"
CALLBACK_LANGUAGE_PREFIX = "set_lang_"
CALLBACK_SKIP_ATTACHMENTS = "skip_attachments"
CALLBACK_FINISH_ATTACHMENTS = "finish_attachments"
CALLBACK_CHANGE_STATUS = f"{MENU_PREFIX}change_status"
CALLBACK_STATUS_PREFIX = "status_"
CALLBACK_INFRA_ACTION_PREFIX = "infra_action_"
CALLBACK_INFRA_TYPE_PREFIX = "infra_type_"
CALLBACK_INFRA_CONFIRM = f"{MENU_PREFIX}infra_confirm"
CALLBACK_INFRA_CANCEL = f"{MENU_PREFIX}infra_cancel"

# Ticket detail callbacks
CALLBACK_TICKET_DETAIL = "ticket_detail_"
CALLBACK_TICKET_REPLY = "ticket_reply_"
CALLBACK_TICKET_COMMENTS = "ticket_comments_"
CALLBACK_TICKET_HISTORY = "ticket_history_"
CALLBACK_TICKET_ATTACHMENTS = "ticket_attachments_"
CALLBACK_TICKET_PRIORITY = "ticket_priority_"
CALLBACK_TICKET_ASSIGN = "ticket_assign_"

# Priority callbacks
CALLBACK_PRIORITY_PREFIX = "priority_"

# User/Agent selection callbacks
CALLBACK_USER_PREFIX = "user_"

# Search and filter callbacks
CALLBACK_SEARCH = f"{MENU_PREFIX}search"
CALLBACK_SEARCH_FILTER_STATUS = "search_status_"
CALLBACK_SEARCH_FILTER_PRIORITY = "search_priority_"
CALLBACK_SEARCH_FILTER_CATEGORY = "search_category_"
CALLBACK_SEARCH_FILTER_DATE = "search_date_"

# Bulk action callbacks
CALLBACK_BULK_ACTION = f"{MENU_PREFIX}bulk"
CALLBACK_BULK_SELECT = "bulk_select_"
CALLBACK_BULK_CONFIRM = "bulk_confirm"
CALLBACK_BULK_CANCEL = "bulk_cancel"

# SLA Alerts callbacks
CALLBACK_ALERTS = f"{MENU_PREFIX}alerts"
CALLBACK_ALERTS_FILTER_WARNING = "alerts_filter_warning"
CALLBACK_ALERTS_FILTER_BREACH = "alerts_filter_breach"
CALLBACK_ALERTS_FILTER_ALL = "alerts_filter_all"
CALLBACK_ALERTS_TICKET = "alerts_ticket_"

# SLA Report callbacks
CALLBACK_SLA_REPORT = f"{MENU_PREFIX}sla_report"
CALLBACK_SLA_REPORT_COMPLIANCE = "sla_report_compliance"
CALLBACK_SLA_REPORT_BY_PRIORITY = "sla_report_by_priority"

__all__ = [
    "CALLBACK_NEW_TICKET",
    "CALLBACK_MY_TICKETS",
    "CALLBACK_TRACK_TICKET",
    "CALLBACK_HELP",
    "CALLBACK_LANGUAGE",
    "CALLBACK_LOGIN",
    "CALLBACK_LOGOUT",
    "CALLBACK_CATEGORY_PREFIX",
    "CALLBACK_BRANCH_PREFIX",
    "CALLBACK_LANGUAGE_PREFIX",
    "CALLBACK_SKIP_ATTACHMENTS",
    "CALLBACK_FINISH_ATTACHMENTS",
    "CALLBACK_CHANGE_STATUS",
    "CALLBACK_STATUS_PREFIX",
    "CALLBACK_INFRASTRUCTURE",
    "CALLBACK_INFRA_ACTION_PREFIX",
    "CALLBACK_INFRA_TYPE_PREFIX",
    "CALLBACK_INFRA_CONFIRM",
    "CALLBACK_INFRA_CANCEL",
    "CALLBACK_TICKET_DETAIL",
    "CALLBACK_TICKET_REPLY",
    "CALLBACK_TICKET_COMMENTS",
    "CALLBACK_TICKET_HISTORY",
    "CALLBACK_TICKET_ATTACHMENTS",
    "CALLBACK_TICKET_PRIORITY",
    "CALLBACK_TICKET_ASSIGN",
    "CALLBACK_PRIORITY_PREFIX",
    "CALLBACK_USER_PREFIX",
    "CALLBACK_SEARCH",
    "CALLBACK_SEARCH_FILTER_STATUS",
    "CALLBACK_SEARCH_FILTER_PRIORITY",
    "CALLBACK_SEARCH_FILTER_CATEGORY",
    "CALLBACK_SEARCH_FILTER_DATE",
    "CALLBACK_BULK_ACTION",
    "CALLBACK_BULK_SELECT",
    "CALLBACK_BULK_CONFIRM",
    "CALLBACK_BULK_CANCEL",
    "CALLBACK_ALERTS",
    "CALLBACK_ALERTS_FILTER_WARNING",
    "CALLBACK_ALERTS_FILTER_BREACH",
    "CALLBACK_ALERTS_FILTER_ALL",
    "CALLBACK_ALERTS_TICKET",
    "CALLBACK_SLA_REPORT",
    "CALLBACK_SLA_REPORT_COMPLIANCE",
    "CALLBACK_SLA_REPORT_BY_PRIORITY",
]

