"""
Callback data constants used throughout the Telegram bot.
"""

MENU_PREFIX = "menu_"
CALLBACK_NEW_TICKET = f"{MENU_PREFIX}new_ticket"
CALLBACK_MY_TICKETS = f"{MENU_PREFIX}my_tickets"
CALLBACK_TRACK_TICKET = f"{MENU_PREFIX}track_ticket"
CALLBACK_HELP = f"{MENU_PREFIX}help"
CALLBACK_LANGUAGE = f"{MENU_PREFIX}language"
CALLBACK_LOGIN = f"{MENU_PREFIX}login"
CALLBACK_LOGOUT = f"{MENU_PREFIX}logout"

CALLBACK_CATEGORY_PREFIX = "category_"
CALLBACK_LANGUAGE_PREFIX = "set_lang_"
CALLBACK_SKIP_ATTACHMENTS = "skip_attachments"

__all__ = [
    "CALLBACK_NEW_TICKET",
    "CALLBACK_MY_TICKETS",
    "CALLBACK_TRACK_TICKET",
    "CALLBACK_HELP",
    "CALLBACK_LANGUAGE",
    "CALLBACK_LOGIN",
    "CALLBACK_LOGOUT",
    "CALLBACK_CATEGORY_PREFIX",
    "CALLBACK_LANGUAGE_PREFIX",
    "CALLBACK_SKIP_ATTACHMENTS",
]

